# -*- coding: utf-8 -*-
"""20230913_4120E018.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1172wRuYp8HvJ2lszfcJRru2TYNbqw0ec
"""

3**211